### ISSUE TITLE
Document logging of extra data

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/xlt-documentation#26] opened 2021-01-14 08:32 UTC
Document `Session.getCurrent().getValueLog().put("","");`

**Comment by rschwietzke** [comment] 2021-01-22 17:43
See also https://lab.xceptance.de/releases/xlt/latest/release-notes/4.8.x.html#toc-release-overview and checkout the headline: *General value log in result browser*

**Comment by js-xc** [comment] 2024-01-30 12:04
Duplicate of #143

**Closed by js-xc** 2024-01-30 12:04 UTC
